services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - './docker/rabbitmq:/etc/rabbitmq/entrypoint'
    networks:
      - internal

networks:
  internal:
    driver: bridge