services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - './docker/rabbitmq:/etc/rabbitmq/entrypoint'
    networks:
      - internal

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PasswordLocalhost"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mssql-data: {}